### ISSUE TITLE
🐛 Jobs get stuck in QUEUED state

### ISSUE THREAD

**Issue by andricDu** [icgc-argo/workflow-management#183]
This bug appears in Prod.

During the azure transfer, some jobs got stuck in the QUEUED state. Restarting the scheduler did not fix the issue. Restarting management causes the jobs to continue on from QUEUED to RUNNING. 

Something within management requires the service to be kicked before consuming the messages from the the rabbit queue. If I had to guess its messages that are read but not acked that management won't process until next time it is started. 

@UmmulkiramR is still investigating, timeout might be the cause.

**Comment by andricDu** [comment]
Issue occurred. This is what I see before restarting workflow management or scheduler:
![Screenshot from 2021-08-31 10-39-20](https://user-images.githubusercontent.com/6350043/131523039-eeb04a41-8d50-4a99-b130-1caaf7744d2e.png)

**Comment by andricDu** [comment]
after restart: 

![Screenshot from 2021-08-31 10-42-46](https://user-images.githubusercontent.com/6350043/131523710-7a3744a3-4046-4016-ad6e-3cc7f26687d3.png)

followed by:

![Screenshot from 2021-08-31 10-44-39](https://user-images.githubusercontent.com/6350043/131523834-5f21c685-0da7-425b-b264-7dfb35022e77.png)

**Comment by rosibaj** [comment]
@lindaxiang we were not able to replicate this in the past 2 weeks.   Can you continue to monitor and update this ticket exactly when you see it? That way we can check the logs when it is happening.

**Comment by lindaxiang** [comment]
Thanks @rosibaj Yes. I will keep monitoring and updating this ticket if the same issue happens.

**Comment by joneubank** [comment]
Reviewing tickets today, this is reported as still occasionally occurring and should remain open for investigation.

**Comment by UmmulkiramR** [comment]
From version 3.8.15 onward rabbitmq has introduced a consumer_timeout. This is the max time until which the messages on the queue can remain unacknowledged. By default this is on and is 30 mins. If a consumer fails to acknowledge a message within this time limit the connection to that consumer is dropped and the message is re-queued which is what is happening here too. 

This timeout value is increased on prod and has been under monitoring for a few days now. We haven't had any disconnection issues due to unacknowledged messages so far. We'll wait a for a few more days and then update the helm chart with the new timeout value

**Comment by UmmulkiramR** [comment]
Closing the ticket as we no longer faced the issue after the fix was applied.
