### ISSUE TITLE
🐛 Can't start runs in Prod by both graphQL call and WES UI

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-management#204]
## Describe the bug
I was trying to send graphQL mutation call and from WES UI to start test runs in both Prod, QA and Dev
- the ones in Dev and QA went through successfully and complete as expected.
- However the one in Prod keeps getting `connection errors`(thanks to Ummulkiram, she helped me looking into the log and found the error message)

## Steps To Reproduce
Steps to reproduce the behaviour:
1. Go to 'https://wes.rdpc.cancercollaboratory.org/runs'
2. Click on 'NEW RUN'
3. Fill in the following
Workflow URL: `https://github.com/nextflow-io/hello`
Workflow Engine Params:
```
{
    "projectDir": "/nfs-1-c1/projects",
    "launchDir": "/nfs-1-c1/launch",
    "workDir": "/nfs-1-c1/launch/work",
    "revision": "master"
}
```
4. Click `SUBMIT RUN`
5. No run is started

## Expected behaviour
A new run shall be started and run through to completion.

**Comment by UmmulkiramR** [comment]
The connection of the workflow management consumer to the rabbitmq queue broke because of which it stopped receiving the run commands. Restarting the pod fixed this. 
The reason for this abrupt disconnection is unknown. We can probably put some sort of monitoring/logging in place for detection of such events and add some configurations for connection recovery. But this would require more discussion with @joneubank  and the devops team after which we can take this up in a separate ticket.
