### ISSUE TITLE
Fix Model Tee in RDPC Dev/QA/Prod

### ISSUE THREAD

**Issue by b-f-chan** [icgc-argo/workflow-management#205]
Model Tee is currently not operating currently in RDPC Dev and QA (and as such, is assumed to not be properly working in Prod either).  We need to fix and get Model Tee running in all three environments again.

**Comment by UmmulkiramR** [comment]
The submission-song url sent in the input parameter has a trailing forward slash (/) in the end. As a result, Song rejects the url with the error `The request was rejected because the URL contained a potentially malicious String \"//\"` and the DnaAln:dnld:scoreDn task fails.  
The forward slash at the end of the url needs to be dropped before sending it in the input parameters.

**Comment by Buwujiu** [comment]
Issue is fixed, will close now.
